### ISSUE TITLE
about the performance evaluation code of the predicted group motion model

### ISSUE THREAD

**Issue by Ashtray4** [CMU-TBD/Group_baed_navigation_v1#2]
Thanks to the author for such an excellent work, but I want to know where the performance evaluation code of the predicted group motion model is, it seems that the repository does not include this part. I look forward to your answer and guidance, thank you
<img width="588" alt="预测群组运动" src="https://github.com/user-attachments/assets/23d115d9-fb3e-472a-a90c-d6f389794cf6">

**Comment by allanwangliqian** [comment]
Hi. Thank you!

Indeed I did not include the code to this part of the paper but it is on my computer. We recently started to work on a future iteration of this paper and are in the process of doing some cleaning up. Expect a future version of this code with the evaluation code for this part in a few weeks. I will also let you know when it happens.

**Comment by Ashtray4** [comment]
OK, I understand. Thank you for your hard work on this, it will be of great help to me.

**Comment by Ashtray4** [comment]
Hello, I apologize for the disturbance again. While reading your code, I noticed an issue in the function [[link to code](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L86)](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L86): I observed that the return value of `db.fit_predict`  (at [[line 108](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L108)](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L108)) does not always start from 0, and it assigns a value of -1 to noise points. However, I did not find any handling for noise points in this function.

Let’s assume there are 6 people in one frame. Initially, in the function `grouping` (at [[line 143](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L143)](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L143)), `labels = [0, 0, 0, 0, 0, 0]`. After the first clustering round, we assume that `sub_labels = [0, 1, 0, 1, 1, -1]` (at [[line 108](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L108)](https://github.com/CMU-TBD/Group_based_navigation_v1/blob/93b0ca9e78ce50f8ff4fecd51a0366417d13a050/grouping.py#L108)). At this point, after processing, the returned `labels` would be `[0, 1, 0, 1, 1, 0]`, which is clearly an incorrect result. This is because it incorrectly assigns a noise point to a cluster.

I’m not sure if what I’m saying is correct. Thank you for your patience in clarifying this issue!

**Comment by allanwangliqian** [comment]
Hi. No worries. I am happy to answer any questions :)

Thank you for catching this. I realized the comments I put in `_DBScan_grouping` are wrong. In fact, I probably did not read DBSCAN's documentation carefully and just tested fit_predict directly...

I think in my case there will be no "noise points" because I set `min_samples = 1` when initializing DBSCAN, but yes I need to be clearer about this.

**Comment by Ashtray4** [comment]
Oh, I see! I understand now. 

I hadn’t noticed the parameter settings when initializing DBSCAN, and I wasn’t very clear about the meaning of the `min_samples` parameter—this was my oversight. 

Thank you for your explanation! Have a great day! :)
